// <auto-generated />
using System;
using IntihalProjesi.Repositories.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntihalProjesi.Migrations
{
    [DbContext(typeof(OrjinalIntihalDbContext))]
    [Migration("20250509075433_ilkMigrattion")]
    partial class ilkMigrattion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntihalProjesi.Models.BenzerlikSonucu", b =>
                {
                    b.Property<int>("SonucId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SonucId"));

                    b.Property<double>("BenzerlikOrani")
                        .HasColumnType("float");

                    b.Property<int?>("IcerikId")
                        .HasColumnType("int");

                    b.Property<int?>("IkinciDosyaId")
                        .HasColumnType("int");

                    b.Property<int?>("IlkDosyaId")
                        .HasColumnType("int");

                    b.HasKey("SonucId");

                    b.HasIndex("IcerikId");

                    b.HasIndex("IkinciDosyaId");

                    b.HasIndex("IlkDosyaId");

                    b.ToTable("BenzerlikSonuclari");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Bildirim", b =>
                {
                    b.Property<int>("BildirimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BildirimId"));

                    b.Property<int?>("IcerikId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Okundu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("BildirimId");

                    b.HasIndex("IcerikId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Bildirimler");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Dosya", b =>
                {
                    b.Property<int>("DosyaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DosyaId"));

                    b.Property<string>("CleanedPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IcerikId")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("DosyaId");

                    b.HasIndex("IcerikId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Dosyalar");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Icerik", b =>
                {
                    b.Property<int>("IcerikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IcerikId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IcerikTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("IcerikId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Icerikler");
                });

            modelBuilder.Entity("IntihalProjesi.Models.JplagJob", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IcerikId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobId");

                    b.HasIndex("IcerikId");

                    b.ToTable("JplagJobs");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            KullaniciId = 1,
                            Ad = "emre",
                            Eposta = "emre@gmail.com",
                            Rol = "Admin",
                            Sifre = "emre123",
                            Soyad = "almamış"
                        });
                });

            modelBuilder.Entity("IntihalProjesi.Models.BenzerlikSonucu", b =>
                {
                    b.HasOne("IntihalProjesi.Models.Icerik", "Icerik")
                        .WithMany()
                        .HasForeignKey("IcerikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntihalProjesi.Models.Dosya", "IkinciDosya")
                        .WithMany()
                        .HasForeignKey("IkinciDosyaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntihalProjesi.Models.Dosya", "IlkDosya")
                        .WithMany()
                        .HasForeignKey("IlkDosyaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Icerik");

                    b.Navigation("IkinciDosya");

                    b.Navigation("IlkDosya");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Bildirim", b =>
                {
                    b.HasOne("IntihalProjesi.Models.Icerik", null)
                        .WithMany("Bildirimler")
                        .HasForeignKey("IcerikId");

                    b.HasOne("IntihalProjesi.Models.Kullanici", "Kullanici")
                        .WithMany("Bildirimler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Dosya", b =>
                {
                    b.HasOne("IntihalProjesi.Models.Icerik", "Icerik")
                        .WithMany("Dosyalar")
                        .HasForeignKey("IcerikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntihalProjesi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Icerik");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Icerik", b =>
                {
                    b.HasOne("IntihalProjesi.Models.Kullanici", "Kullanici")
                        .WithMany("Icerikler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("IntihalProjesi.Models.JplagJob", b =>
                {
                    b.HasOne("IntihalProjesi.Models.Icerik", "Icerik")
                        .WithMany("JplagJobs")
                        .HasForeignKey("IcerikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icerik");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Icerik", b =>
                {
                    b.Navigation("Bildirimler");

                    b.Navigation("Dosyalar");

                    b.Navigation("JplagJobs");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Kullanici", b =>
                {
                    b.Navigation("Bildirimler");

                    b.Navigation("Icerikler");
                });
#pragma warning restore 612, 618
        }
    }
}
